spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 最重要的是這行，讓雲端環境執行專屬的 data-prod.sql
spring.sql.init.data-locations=classpath:data-prod.sql
